### PR TITLE
Allow warnings in PHPCS linter

### PR DESCRIPTION
**Pull request by neild3r**
Now we are heavier on PSR we should allow the showing of warnings in our linters.

### CODE REVIEW

**Comment by dmnc** [comment]
What's the effect of this?

**Comment by neild3r** [comment]
You get warnings in your sublime linter for things like line length and stuff. For me a I get yellow marks instead of red when it's a warning .

**Comment by dmnc** [comment]
Ah ok. So its basically enabling the SHOULD rules?

On Friday, 16 October 2015, Neil Brayfield notifications@github.com wrote:

> You get warnings in your sublime linter for things like line length and
> stuff. For me a I get yellow marks instead of red when it's a warning .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/D3R/standards/pull/2#issuecomment-148715465.

## 

Dominic Morgan
D3R Ltd
0333 800 2288
dom@d3r.com
http://d3r.com

**Comment by neild3r** [comment]
Yep

**Comment by dave470003** [comment]
BUMP

**Pull request merged**
